export const CREATE_PRATO = "CREATE_PRATO";
export const RETRIEVE_PRATOS = "RETRIEVE_PRATOS";
export const UPDATE_PRATO = "UPDATE_PRATO";
export const DELETE_PRATO = "DELETE_PRATO";
export const DELETE_ALL_PRATOS = "DELETE_ALL_PRATOS";